### ISSUE TITLE
V2 schena docs for `releases` block is incomplete

### ISSUE THREAD

**Issue by kdvolder** [cloudfoundry/docs-bosh#330]
V2 schema docs for 'releases': 

https://bosh.io/docs/manifest-v2.html#releases

There is no mention of attributes 'url' and 'sha1' although these seem to be valid (used in the cf manifest at least: https://github.com/cloudfoundry/cf-deployment/blob/master/cf-deployment.yml )

**Comment by kdvolder** [comment]
I also suspect the docs for V1 on this is incorrect too, or at least... confusing. 

In the cf example we have this kind of releases:

```
releases:
- name: binary-buildpack
  url: https://bosh.io/d/github.com/cloudfoundry/binary-buildpack-release?v=1.0.13
  version: 1.0.13
  sha1: f894e46d279cd965885f255439ea14188c48306d
```

I.e. all 4 properties `name`, '`url`, `version` and `sha1` are defined.

But the docs (https://bosh.io/docs/deployment-manifest.html#releases) seem to say you have a choice between either (name + version) or (name + url + sha1). So that would mean either:

```
- name: binary-buildpack
  version: 1.0.13
```

or 

```
- name: binary-buildpack
  url: https://bosh.io/d/github.com/cloudfoundry/binary-buildpack-release?v=1.0.13
  sha1: f894e46d279cd965885f255439ea14188c48306d
```

But not the combination of both that we see in the cf manifest.

Please clarify. Thanks.
