### ISSUE TITLE
placement rules did not explain precedence

### ISSUE THREAD

**Issue by fredwangwang** [cloudfoundry/docs-bosh#592]
code snippet from cf-d:
```yaml
addons:
- name: loggregator_agent
  include:
    stemcell:
    - os: ubuntu-xenial
  exclude:
    jobs:
    - name: smoke_tests
      release: cf-smoke-tests
```

From the above example, seems like `exclude` rule takes higher precedence, as `cf-smoke-tests` uses `ubuntu-xenial` as well but does not run `loggregator_agent`.

But when reading the [doc](https://bosh.io/docs/runtime-config/#placement-rules), it did not explain the precedence at all. Probably add a note about precedence for clarity?
